### ISSUE TITLE
Help installing on Windows 10/11

### ISSUE THREAD

**Issue by kw0n** [DravenTec/Twitch-Stream-Recorder#1]
Hi Draven,

I am trying to install this on a Windows computer but am stuck. I am assuming I would be able to just skip step 3 and 4 right?
I installed streamlink (I believe python is included with streamlink so I dont need to install but I could be wrong) , ffmpeg and twitch-cli.

In your instructions, I am stuck at step 7 where I set the self.root_path to  self.root_path = "F:\Twitch_Recordings"

but I noticed this line
'self.twitch_path = '/home/linuxbrew/.linuxbrew/bin/twitch'

What path am I supposed to put here?

Is there any other steps I would be missing?

**Comment by DravenTec** [comment]
Hi kw0n,

I have never tried or tested the whole thing under Windows.

Point 3 and 4 is necessary for the Twitch-cli, if it can be installed differently under Windows you can skip the points. 
For the **self,root_path** it should be possible under Windows with **self.root_path = "F:\\Twitch_Recordings"**

**self.twitch_path = '/home/linuxbrew/.linuxbrew/bin/twitch'** specifies the path to twitch-cli, 
which is used to check if the streamer is online and to get the stream title. 
So here the path to the twitch-cli would have to be specified.

Without the twitch-cli the script does not run. 

You could also just call streamlink again and again until a stream is recognized
streamlink twitch.tv/streamername best -o recorded_stream.mp4
